# This file was generated by GoReleaser. DO NOT EDIT.
cask "kute" do
  version "0.6.0-beta.3"

  on_macos do
    on_intel do
      sha256 "091269f3dd690cdecc648c7222d8905448b516fb9bcf91f2f6ef3b60f67e6727"
      url "https://github.com/kute-dev/kute/releases/download/v#{version}/kute_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "232716915dbe30f48a1bcdaaf591d10ed0e15cda406a4a3b73c1640ed8942861"
      url "https://github.com/kute-dev/kute/releases/download/v#{version}/kute_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "9fa6b8211030029cc864a5237bf3fda97264c8fd47eae3a3d77134eb56a74731"
      url "https://github.com/kute-dev/kute/releases/download/v#{version}/kute_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "0fac3727d1d18e2401391dfdd1ee2b5e9aec5a555481c17f529e0c2387611842"
      url "https://github.com/kute-dev/kute/releases/download/v#{version}/kute_#{version}_linux_arm64.tar.gz"
    end
  end

  name "kute"
  desc "A TUI Kubernetes console, built with Bubble Tea and Lip Gloss."
  homepage "https://github.com/kute-dev/kute"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kute"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
        args: ["-dr", "com.apple.quarantine", "#{staged_path}/kute"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    kute is open-source software and is not currently signed with an
    Apple Developer ID. The Homebrew installation removes the macOS
    quarantine attribute from the installed binary.
  EOS
end
