# This file was generated by GoReleaser. DO NOT EDIT.
cask "kute" do
  version "0.2.0-alpha.2"

  on_macos do
    on_intel do
      sha256 "b36d9f5181aa3873607d47feaf0686f0bc508e7dee52bb0cb35f778a02f62ece"
      url "https://github.com/kute-dev/kute/releases/download/v#{version}/kute_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "14e8deb77cd7093344d70d7c15fdeaa4dae725640ee011fc7992228fadb43cd5"
      url "https://github.com/kute-dev/kute/releases/download/v#{version}/kute_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "b053b35225492fef73b6b41fcc921e56b0245cb3e1e76cadbbfce951be151d67"
      url "https://github.com/kute-dev/kute/releases/download/v#{version}/kute_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "ce80d34d76dabf2dc1636bc4727471ec79de586593912ee39fb94229d5927832"
      url "https://github.com/kute-dev/kute/releases/download/v#{version}/kute_#{version}_linux_arm64.tar.gz"
    end
  end

  name "kute"
  desc "A TUI Kubernetes console, built with Bubble Tea and Lip Gloss."
  homepage "https://github.com/kute-dev/kute"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kute"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
        args: ["-dr", "com.apple.quarantine", "#{staged_path}/kute"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    kute is open-source software and is not currently signed with an
    Apple Developer ID. The Homebrew installation removes the macOS
    quarantine attribute from the installed binary.
  EOS
end
