# This file was generated by GoReleaser. DO NOT EDIT.
cask "kute" do
  version "0.11.3"

  on_macos do
    on_intel do
      sha256 "ff0c77d87ac6502a2fb956a6fd2d292272a40732e19323aafe2e40a807a45001"
      url "https://github.com/kute-dev/kute/releases/download/v#{version}/kute_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "8e1b8fd0847586300987f0f3047cb278a8f8fdb5ed9088bd991fd408ff04da49"
      url "https://github.com/kute-dev/kute/releases/download/v#{version}/kute_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "2fa65bc4fc04cd712be1e8e8282bd0854cbf5a149078e64c7f6e4237fa93e28a"
      url "https://github.com/kute-dev/kute/releases/download/v#{version}/kute_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "7277fa65563f5976b2cd454f342cf2595c3af16fc3e010e6dad92fdb0a33d83e"
      url "https://github.com/kute-dev/kute/releases/download/v#{version}/kute_#{version}_linux_arm64.tar.gz"
    end
  end

  name "kute"
  desc "A TUI Kubernetes console, built with Bubble Tea and Lip Gloss."
  homepage "https://github.com/kute-dev/kute"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kute"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
        args: ["-dr", "com.apple.quarantine", "#{staged_path}/kute"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    kute is open-source software and is not currently signed with an
    Apple Developer ID. The Homebrew installation removes the macOS
    quarantine attribute from the installed binary.
  EOS
end
